### ISSUE TITLE
タイトル画面のデザイン案

### ISSUE THREAD

**Issue by Tomakara483** [MIZUSHIKI/NicoFlick#3]
タイトル画面のデザインを考えてみました！
xCodeの知識は一切ないので、画像だけです。すみません。
クオリティーは低いですが、もしよければ使ってください笑

フォントはフリーフォントの「ニコ角フォント」を使ってみました。
多分ライセンスの面でも大丈夫だとは思います。(ライセンスもあまり詳しくないです)
http://nicofont.pupu.jp/nicokaku-plus.html

つい最近こちらのNicoFlickをインストールしたのですが、めっちゃ楽しくて、凄いはまってます！
これが無料で遊べるなんて嬉しすぎます、ありがとうございます！

![titleScreen](https://user-images.githubusercontent.com/84258105/118384730-87a91000-b643-11eb-8351-415ed4ecdfc7.png)

**Comment by MIZUSHIKI** [comment]
うわー！ありがとうございます！
すみません。コメントされてたのに全然気が付きませんでした。。。

まだ開発版ですが、ちょっと試してみたらこんな感じになりました。
アイコンは、「このアイコンじゃなくても良いな」と思ってるので省いちゃいました。

（Gifだと潰れて見えないですけど、背景にうっすら斜め線が入っていて、じわーっと上にスクロールするのを謎に追加してます。）

タイトルだけ格好良くなっちゃって、他の画面がショボく感じる気もして来ました。
他の画面のデザインどうしようかな。。。

![out](https://user-images.githubusercontent.com/33353602/121353872-4b7a7e00-c969-11eb-97ab-0a7ea69952d9.gif)

<img src="https://user-images.githubusercontent.com/33353602/121353939-5af9c700-c969-11eb-904c-d5b4ca482e40.jpeg" width="300">

**Comment by Tomakara483** [comment]
うおお！使っていただけるなんて嬉しいです、ありがとうございます！
